use_frameworks!

platform :ios, '13.0'

target 'MDGA_Example' do
  pod 'MDGA', :path => '../'
  
  pod 'DJI-SDK-iOS', '~> 4.16.2'
  pod 'DJI-UXSDK-iOS', '~> 4.16.2'
  pod 'DJIWidget'
  
  pod 'SnapKit'


  target 'MDGA_Tests' do
    inherit! :search_paths

    
  end
end
